In [1]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=3)

print(X.shape, y.shape)

(1000, 20) (1000,)


In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

data = pd.read_csv('Instruments.csv')
 
data.head()

data.iloc[:,1:52]
# Create feature and target arrays
X = data.iloc[:,1:52]
y = data['Actor']
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=42)

In [3]:
rf= RandomForestClassifier()
rf.fit(X_train,y_train)
predictions= rf.predict(X_test)



from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))


[[ 2  2  1  3  0  0  0  4  2  1]
 [ 0  4  0  0  2  0  0  1  2  0]
 [ 0  1  0  3  0  0  0  1  2  0]
 [ 2  0  1  4  1  0  0  0  1  0]
 [ 0  0  1  0  2  1  0  0  0  0]
 [ 0  1  1  0  0  4  0  0  2  0]
 [ 0  0  0  0  0  0  0  2  2  0]
 [ 0  1  0  0  0  0  0 13  0  0]
 [ 0  0  0  0  0  0  0  0 12  0]
 [ 0  0  2  1  1  0  0  2  6  3]]


              precision    recall  f1-score   support

       Ajith       0.50      0.13      0.21        15
           D       0.44      0.44      0.44         9
       Kamal       0.00      0.00      0.00         7
      Rajini       0.36      0.44      0.40         9
          SK       0.33      0.50      0.40         4
       Simbu       0.80      0.50      0.62         8
       Surya       0.00      0.00      0.00         4
         VJS       0.57      0.93      0.70        14
        Viay       0.41      1.00      0.59        12
      Vikram       0.75      0.20      0.32        15

    accuracy                           0.45        97
   macro avg     

C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [4]:
rf.predict(data.iloc[0:1,1:52])

array(['SK'], dtype=object)

In [7]:
rf.predict(data.iloc[460:465,1:52])

array(['Vikram', 'Vikram', 'SK', 'VJS', 'Vikram'], dtype=object)